// convpng v7.1
// this file contains all the graphics sources for easy inclusion in a project
#ifndef __symbols_gfx__
#define __symbols_gfx__
#include <stdint.h>

#define symbols_gfx_transparent_color_index 0

#define autonA_width 6
#define autonA_height 7
#define autonA_size 44
extern uint8_t autonA_data[44];
#define autonA ((gfx_sprite_t*)autonA_data)
#define autonASelected_width 6
#define autonASelected_height 7
#define autonASelected_size 44
extern uint8_t autonASelected_data[44];
#define autonASelected ((gfx_sprite_t*)autonASelected_data)
#define autonE_width 6
#define autonE_height 7
#define autonE_size 44
extern uint8_t autonE_data[44];
#define autonE ((gfx_sprite_t*)autonE_data)
#define autonESelected_width 6
#define autonESelected_height 7
#define autonESelected_size 44
extern uint8_t autonESelected_data[44];
#define autonESelected ((gfx_sprite_t*)autonESelected_data)
#define autonT_width 6
#define autonT_height 7
#define autonT_size 44
extern uint8_t autonT_data[44];
#define autonT ((gfx_sprite_t*)autonT_data)
#define autonTSelected_width 6
#define autonTSelected_height 7
#define autonTSelected_size 44
extern uint8_t autonTSelected_data[44];
#define autonTSelected ((gfx_sprite_t*)autonTSelected_data)
#define blueAuton_width 10
#define blueAuton_height 11
#define blueAuton_size 112
extern uint8_t blueAuton_data[112];
#define blueAuton ((gfx_sprite_t*)blueAuton_data)
#define blueTeamTextBox_width 45
#define blueTeamTextBox_height 12
#define blueTeamTextBox_size 542
extern uint8_t blueTeamTextBox_data[542];
#define blueTeamTextBox ((gfx_sprite_t*)blueTeamTextBox_data)
#define bottomPanel_width 64
#define bottomPanel_height 16
#define bottomPanel_size 1026
extern uint8_t bottomPanel_data[1026];
#define bottomPanel ((gfx_sprite_t*)bottomPanel_data)
#define deltaTextBox_width 28
#define deltaTextBox_height 12
#define deltaTextBox_size 338
extern uint8_t deltaTextBox_data[338];
#define deltaTextBox ((gfx_sprite_t*)deltaTextBox_data)
#define deltaXText_width 15
#define deltaXText_height 7
#define deltaXText_size 107
extern uint8_t deltaXText_data[107];
#define deltaXText ((gfx_sprite_t*)deltaXText_data)
#define emptyTower_width 37
#define emptyTower_height 37
#define emptyTower_size 1371
extern uint8_t emptyTower_data[1371];
#define emptyTower ((gfx_sprite_t*)emptyTower_data)
#define genericAuton_width 10
#define genericAuton_height 11
#define genericAuton_size 112
extern uint8_t genericAuton_data[112];
#define genericAuton ((gfx_sprite_t*)genericAuton_data)
#define genericCube_width 37
#define genericCube_height 37
#define genericCube_size 1371
extern uint8_t genericCube_data[1371];
#define genericCube ((gfx_sprite_t*)genericCube_data)
#define genericTeamColor_width 40
#define genericTeamColor_height 10
#define genericTeamColor_size 402
extern uint8_t genericTeamColor_data[402];
#define genericTeamColor ((gfx_sprite_t*)genericTeamColor_data)
#define greenAuton_width 10
#define greenAuton_height 11
#define greenAuton_size 112
extern uint8_t greenAuton_data[112];
#define greenAuton ((gfx_sprite_t*)greenAuton_data)
#define greenCube_width 37
#define greenCube_height 37
#define greenCube_size 1371
extern uint8_t greenCube_data[1371];
#define greenCube ((gfx_sprite_t*)greenCube_data)
#define greenTextBox_width 45
#define greenTextBox_height 11
#define greenTextBox_size 497
extern uint8_t greenTextBox_data[497];
#define greenTextBox ((gfx_sprite_t*)greenTextBox_data)
#define greenTextBoxLong_width 92
#define greenTextBoxLong_height 11
#define greenTextBoxLong_size 1014
extern uint8_t greenTextBoxLong_data[1014];
#define greenTextBoxLong ((gfx_sprite_t*)greenTextBoxLong_data)
#define neutralTeamBox_width 45
#define neutralTeamBox_height 12
#define neutralTeamBox_size 542
extern uint8_t neutralTeamBox_data[542];
#define neutralTeamBox ((gfx_sprite_t*)neutralTeamBox_data)
#define orangeCube_width 37
#define orangeCube_height 37
#define orangeCube_size 1371
extern uint8_t orangeCube_data[1371];
#define orangeCube ((gfx_sprite_t*)orangeCube_data)
#define orangeTextBox_width 45
#define orangeTextBox_height 11
#define orangeTextBox_size 497
extern uint8_t orangeTextBox_data[497];
#define orangeTextBox ((gfx_sprite_t*)orangeTextBox_data)
#define orangeTextBoxLong_width 92
#define orangeTextBoxLong_height 11
#define orangeTextBoxLong_size 1014
extern uint8_t orangeTextBoxLong_data[1014];
#define orangeTextBoxLong ((gfx_sprite_t*)orangeTextBoxLong_data)
#define plusMinusZero_width 22
#define plusMinusZero_height 7
#define plusMinusZero_size 156
extern uint8_t plusMinusZero_data[156];
#define plusMinusZero ((gfx_sprite_t*)plusMinusZero_data)
#define purpleCube_width 37
#define purpleCube_height 37
#define purpleCube_size 1371
extern uint8_t purpleCube_data[1371];
#define purpleCube ((gfx_sprite_t*)purpleCube_data)
#define purpleTextBox_width 45
#define purpleTextBox_height 11
#define purpleTextBox_size 497
extern uint8_t purpleTextBox_data[497];
#define purpleTextBox ((gfx_sprite_t*)purpleTextBox_data)
#define purpleTextBoxLong_width 92
#define purpleTextBoxLong_height 11
#define purpleTextBoxLong_size 1014
extern uint8_t purpleTextBoxLong_data[1014];
#define purpleTextBoxLong ((gfx_sprite_t*)purpleTextBoxLong_data)
#define recommendationScore_width 37
#define recommendationScore_height 11
#define recommendationScore_size 409
extern uint8_t recommendationScore_data[409];
#define recommendationScore ((gfx_sprite_t*)recommendationScore_data)
#define redAuton_width 10
#define redAuton_height 11
#define redAuton_size 112
extern uint8_t redAuton_data[112];
#define redAuton ((gfx_sprite_t*)redAuton_data)
#define redTeamTextBox_width 45
#define redTeamTextBox_height 12
#define redTeamTextBox_size 542
extern uint8_t redTeamTextBox_data[542];
#define redTeamTextBox ((gfx_sprite_t*)redTeamTextBox_data)
#define redTextBox_width 45
#define redTextBox_height 11
#define redTextBox_size 497
extern uint8_t redTextBox_data[497];
#define redTextBox ((gfx_sprite_t*)redTextBox_data)
#define scoreTextBox_width 45
#define scoreTextBox_height 11
#define scoreTextBox_size 497
extern uint8_t scoreTextBox_data[497];
#define scoreTextBox ((gfx_sprite_t*)scoreTextBox_data)
#define shortGreenTextBox_width 28
#define shortGreenTextBox_height 11
#define shortGreenTextBox_size 310
extern uint8_t shortGreenTextBox_data[310];
#define shortGreenTextBox ((gfx_sprite_t*)shortGreenTextBox_data)
#define shortOrangeTextBox_width 28
#define shortOrangeTextBox_height 11
#define shortOrangeTextBox_size 310
extern uint8_t shortOrangeTextBox_data[310];
#define shortOrangeTextBox ((gfx_sprite_t*)shortOrangeTextBox_data)
#define shortPurpleTextBox_width 28
#define shortPurpleTextBox_height 11
#define shortPurpleTextBox_size 310
extern uint8_t shortPurpleTextBox_data[310];
#define shortPurpleTextBox ((gfx_sprite_t*)shortPurpleTextBox_data)
#define shortRedTextBox_width 28
#define shortRedTextBox_height 11
#define shortRedTextBox_size 310
extern uint8_t shortRedTextBox_data[310];
#define shortRedTextBox ((gfx_sprite_t*)shortRedTextBox_data)
#define stackedCube_width 37
#define stackedCube_height 37
#define stackedCube_size 1371
extern uint8_t stackedCube_data[1371];
#define stackedCube ((gfx_sprite_t*)stackedCube_data)
#define towerAdd_width 37
#define towerAdd_height 37
#define towerAdd_size 1371
extern uint8_t towerAdd_data[1371];
#define towerAdd ((gfx_sprite_t*)towerAdd_data)
#define towerRemove_width 37
#define towerRemove_height 37
#define towerRemove_size 1371
extern uint8_t towerRemove_data[1371];
#define towerRemove ((gfx_sprite_t*)towerRemove_data)
#define sizeof_symbols_gfx_pal 512
extern uint16_t symbols_gfx_pal[256];
#define gray 255
#define gold 254
#define silver 253
#define bronze 252

#endif
